package com.markethub.review;
import com.markethub.auth.JwtService; import com.markethub.category.*; import com.markethub.order.*; import com.markethub.product.*; import com.markethub.user.*; import com.markethub.vendor.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.MediaType; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.UUID;
import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Transactional
class ReviewWorkflowTests {
 @Autowired MockMvc mvc; @Autowired ReviewRepository reviews; @Autowired UserRepository users; @Autowired VendorRepository vendors; @Autowired CategoryRepository categories; @Autowired ProductRepository products; @Autowired OrderRepository orders; @Autowired OrderItemRepository items; @Autowired PasswordEncoder encoder; @Autowired JwtService jwt;
 @Test void reviewSavesCorrectly(){Fixture f=fixture("save");Review r=reviews.saveAndFlush(new Review(f.customer,f.product,5,"Excellent"));assertThat(r.getId()).isNotNull();assertThat(r.getRating()).isEqualTo(5);assertThat(r.getCreatedAt()).isNotNull();}
 @Test void databaseRejectsInvalidRating(){Fixture f=fixture("constraint");assertThatThrownBy(()->reviews.saveAndFlush(new Review(f.customer,f.product,0,"Invalid"))).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void duplicateCustomerProductIsRejectedByDatabase(){Fixture f=fixture("unique");reviews.saveAndFlush(new Review(f.customer,f.product,4,"First"));assertThatThrownBy(()->reviews.saveAndFlush(new Review(f.customer,f.product,5,"Second"))).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void deliveredCustomerCanReviewPurchasedProduct()throws Exception{Fixture f=fixture("create");purchase(f,OrderStatus.DELIVERED);create(f.customer,f.product,5," Great ").andExpect(status().isCreated()).andExpect(jsonPath("$.rating").value(5)).andExpect(jsonPath("$.comment").value("Great"));}
 @Test void customerWithoutPurchaseCannotReview()throws Exception{Fixture f=fixture("no-purchase");create(f.customer,f.product,4,"No order").andExpect(status().isForbidden());}
 @Test void undeliveredOrderCannotBeReviewed()throws Exception{Fixture f=fixture("pending");purchase(f,OrderStatus.SHIPPED);create(f.customer,f.product,4,"Too early").andExpect(status().isForbidden());}
 @Test void duplicateReviewReturnsConflict()throws Exception{Fixture f=fixture("twice");purchase(f,OrderStatus.DELIVERED);create(f.customer,f.product,4,"First").andExpect(status().isCreated());create(f.customer,f.product,5,"Again").andExpect(status().isConflict());}
 @Test void customerCannotReviewOwnVendorProduct()throws Exception{Fixture f=fixture("own");f.vendor.getUser().setRole(UserRole.CUSTOMER);users.saveAndFlush(f.vendor.getUser());Fixture own=new Fixture(f.vendor.getUser(),f.vendor,f.product);purchase(own,OrderStatus.DELIVERED);create(own.customer,own.product,5,"Mine").andExpect(status().isForbidden());}
 @Test void invalidRatingIsRejected()throws Exception{Fixture f=fixture("invalid");purchase(f,OrderStatus.DELIVERED);create(f.customer,f.product,6,"Invalid").andExpect(status().isBadRequest()).andExpect(jsonPath("$.errors.rating").exists());}
 @Test void unauthenticatedAndVendorAreRejected()throws Exception{Fixture f=fixture("roles");mvc.perform(post(url(f.product)).contentType(MediaType.APPLICATION_JSON).content(body(4,"Test"))).andExpect(status().isUnauthorized());mvc.perform(post(url(f.product)).header("Authorization",token(f.vendor.getUser())).contentType(MediaType.APPLICATION_JSON).content(body(4,"Test"))).andExpect(status().isForbidden());}
 @Test void customerUpdatesOwnButNotAnotherReview()throws Exception{Fixture f=fixture("update");reviews.saveAndFlush(new Review(f.customer,f.product,3,"Old"));mvc.perform(put(url(f.product)+"/me").header("Authorization",token(f.customer)).contentType(MediaType.APPLICATION_JSON).content(body(5,"New"))).andExpect(status().isOk()).andExpect(jsonPath("$.rating").value(5));User other=user("other-update",UserRole.CUSTOMER);mvc.perform(put(url(f.product)+"/me").header("Authorization",token(other)).contentType(MediaType.APPLICATION_JSON).content(body(4,"Other"))).andExpect(status().isNotFound());}
 @Test void customerDeletesOwnAndMissingReviewIsNotFound()throws Exception{Fixture f=fixture("delete");reviews.saveAndFlush(new Review(f.customer,f.product,4,"Delete"));mvc.perform(delete(url(f.product)+"/me").header("Authorization",token(f.customer))).andExpect(status().isNoContent());mvc.perform(delete(url(f.product)+"/me").header("Authorization",token(f.customer))).andExpect(status().isNotFound());}
 @Test void publicListingIsSafeWithCorrectSummary()throws Exception{Fixture f=fixture("listing");reviews.saveAndFlush(new Review(f.customer,f.product,5,"Excellent"));reviews.saveAndFlush(new Review(user("second-list",UserRole.CUSTOMER),f.product,3,"Okay"));mvc.perform(get(url(f.product))).andExpect(status().isOk()).andExpect(jsonPath("$.reviewCount").value(2)).andExpect(jsonPath("$.averageRating").value(4.0)).andExpect(jsonPath("$.content[0].customerName").exists()).andExpect(jsonPath("$.content[0].email").doesNotExist()).andExpect(jsonPath("$.content[0].customerId").doesNotExist()).andExpect(jsonPath("$.content[0].phone").doesNotExist());}
 @Test void publicListingPaginates()throws Exception{Fixture f=fixture("page");reviews.saveAndFlush(new Review(f.customer,f.product,5,"One"));reviews.saveAndFlush(new Review(user("page-two",UserRole.CUSTOMER),f.product,4,"Two"));mvc.perform(get(url(f.product)).param("page","0").param("size","1")).andExpect(status().isOk()).andExpect(jsonPath("$.content.length()").value(1)).andExpect(jsonPath("$.totalElements").value(2)).andExpect(jsonPath("$.totalPages").value(2));}
 @Test void productResponseIncludesRatingSummary()throws Exception{Fixture f=fixture("summary");reviews.saveAndFlush(new Review(f.customer,f.product,5,"Five"));reviews.saveAndFlush(new Review(user("summary-two",UserRole.CUSTOMER),f.product,4,"Four"));mvc.perform(get("/api/products/{id}",f.product.getId())).andExpect(status().isOk()).andExpect(jsonPath("$.reviewCount").value(2)).andExpect(jsonPath("$.averageRating").value(4.5));}
 private org.springframework.test.web.servlet.ResultActions create(User u,Product p,int rating,String comment)throws Exception{return mvc.perform(post(url(p)).header("Authorization",token(u)).contentType(MediaType.APPLICATION_JSON).content(body(rating,comment)));}
 private String url(Product p){return "/api/products/"+p.getId()+"/reviews";} private String body(int r,String c){return "{\"rating\":"+r+",\"comment\":\""+c+"\"}";} private String token(User u){return "Bearer "+jwt.generateToken(u);}
 private Fixture fixture(String key){String k=key+"-"+UUID.randomUUID();Vendor v=vendor(k+"-vendor");User c=user(k+"-customer",UserRole.CUSTOMER);Category cat=categories.saveAndFlush(new Category("Category "+k,k,"Description"));Product p=products.saveAndFlush(new Product(v,cat,"Product "+k,"Description",BigDecimal.TEN,10,null,ProductStatus.ACTIVE));return new Fixture(c,v,p);}
 private User user(String key,UserRole role){return users.saveAndFlush(new User("Test","Customer",key+"@example.com",encoder.encode("Password123"),role));}
 private Vendor vendor(String key){Vendor v=new Vendor(user(key,UserRole.VENDOR),"Store "+key,"Description","123");v.setStatus(VendorStatus.APPROVED);return vendors.saveAndFlush(v);}
 private void purchase(Fixture f,OrderStatus status){Order o=new Order(f.customer,"MH-"+UUID.randomUUID(),BigDecimal.TEN,BigDecimal.ZERO,PaymentMethod.CASH_ON_DELIVERY,"Test Customer","0771234567","10 Main Street",null,"Colombo","Colombo","00100");o.setStatus(status);o=orders.saveAndFlush(o);OrderItem i=new OrderItem(o,f.product.getId(),f.vendor.getId(),f.product.getName(),BigDecimal.TEN,1);i.setStatus(status);items.saveAndFlush(i);}
 private record Fixture(User customer,Vendor vendor,Product product){}
}