package com.markethub.order;

import com.markethub.address.*; import com.markethub.auth.JwtService; import com.markethub.cart.*; import com.markethub.category.*; import com.markethub.product.*; import com.markethub.user.*; import com.markethub.vendor.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.*;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Transactional
class OrderWorkflowTests {
 @Autowired MockMvc mvc; @Autowired UserRepository users; @Autowired VendorRepository vendors; @Autowired CategoryRepository categories; @Autowired ProductRepository products; @Autowired CartRepository carts; @Autowired CartItemRepository cartItems; @Autowired AddressRepository addresses; @Autowired OrderRepository orders; @Autowired OrderItemRepository orderItems; @Autowired PasswordEncoder encoder; @Autowired JwtService jwt;

 @Test void orderAndSnapshotsPersistWithTotals(){User c=user("order-persist@example.com",UserRole.CUSTOMER);Address a=address(c);Order o=orders.saveAndFlush(new Order(c,"MH-PERSIST-1",new BigDecimal("100"),new BigDecimal("300"),PaymentMethod.CASH_ON_DELIVERY,a.getFullName(),a.getPhone(),a.getAddressLine1(),null,a.getCity(),a.getDistrict(),a.getPostalCode()));OrderItem i=orderItems.saveAndFlush(new OrderItem(o,11L,22L,"Snapshot",new BigDecimal("50"),2));assertThat(orders.findById(o.getId()).orElseThrow().getTotal()).isEqualByComparingTo("400");assertThat(i.getProductName()).isEqualTo("Snapshot");assertThat(i.getSubtotal()).isEqualByComparingTo("100");}

 @Test void customerChecksOutUsingCurrentPriceFeeAndSnapshots() throws Exception {User c=user("checkout@example.com",UserRole.CUSTOMER);Address a=address(c);Product p=product("Checkout",5,"100",ProductStatus.ACTIVE,VendorStatus.APPROVED,true);add(c,p,2);p.setPrice(new BigDecimal("125"));products.saveAndFlush(p);mvc.perform(post("/api/orders/checkout").header("Authorization",token(c)).contentType(MediaType.APPLICATION_JSON).content(checkout(a))).andExpect(status().isCreated()).andExpect(jsonPath("$.subtotal").value(250.00)).andExpect(jsonPath("$.deliveryFee").value(300.00)).andExpect(jsonPath("$.total").value(550.00)).andExpect(jsonPath("$.orderNumber").value(org.hamcrest.Matchers.startsWith("MH-")));Order o=orders.findAll().get(0);OrderItem i=orderItems.findByOrderIdOrderByIdAsc(o.getId()).get(0);assertThat(i.getUnitPrice()).isEqualByComparingTo("125");assertThat(i.getProductName()).isEqualTo("Checkout");}

 @Test void checkoutRejectsUnauthenticatedVendorEmptyCartAndForeignAddress() throws Exception {User c=user("empty-order@example.com",UserRole.CUSTOMER);Address a=address(c);mvc.perform(post("/api/orders/checkout").contentType(MediaType.APPLICATION_JSON).content(checkout(a))).andExpect(status().isUnauthorized());User v=user("order-vendor@example.com",UserRole.VENDOR);mvc.perform(post("/api/orders/checkout").header("Authorization",token(v)).contentType(MediaType.APPLICATION_JSON).content(checkout(a))).andExpect(status().isForbidden());mvc.perform(post("/api/orders/checkout").header("Authorization",token(c)).contentType(MediaType.APPLICATION_JSON).content(checkout(a))).andExpect(status().isConflict());User other=user("foreign-address-order@example.com",UserRole.CUSTOMER);Product p=product("Foreign address",2,"10",ProductStatus.ACTIVE,VendorStatus.APPROVED,true);add(c,p,1);Address foreign=address(other);mvc.perform(post("/api/orders/checkout").header("Authorization",token(c)).contentType(MediaType.APPLICATION_JSON).content(checkout(foreign))).andExpect(status().isForbidden());}

 @Test void checkoutRejectsUnavailableProductsAndInsufficientStock() throws Exception {assertRejected("inactive",ProductStatus.INACTIVE,VendorStatus.APPROVED,true,1,1);assertRejected("archived",ProductStatus.ARCHIVED,VendorStatus.APPROVED,true,1,1);assertRejected("suspended",ProductStatus.ACTIVE,VendorStatus.SUSPENDED,true,1,1);assertRejected("category",ProductStatus.ACTIVE,VendorStatus.APPROVED,false,1,1);assertRejected("stock",ProductStatus.ACTIVE,VendorStatus.APPROVED,true,1,2);}

 @Test void successfulCheckoutReducesStockMarksOutOfStockClearsCartAndNumbersAreUnique() throws Exception {User c=user("stock-checkout@example.com",UserRole.CUSTOMER);Address a=address(c);Product p=product("Exact stock",2,"20",ProductStatus.ACTIVE,VendorStatus.APPROVED,true);add(c,p,2);checkout(c,a).andExpect(status().isCreated());assertThat(products.findById(p.getId()).orElseThrow().getStockQuantity()).isZero();assertThat(products.findById(p.getId()).orElseThrow().getStatus()).isEqualTo(ProductStatus.OUT_OF_STOCK);assertThat(cartItems.count()).isZero();Product p2=product("Second order",1,"10",ProductStatus.ACTIVE,VendorStatus.APPROVED,true);add(c,p2,1);checkout(c,a).andExpect(status().isCreated());assertThat(orders.findAll()).extracting(Order::getOrderNumber).doesNotHaveDuplicates();}

 @Test void invalidCartItemPreventsPartialOrderStockChangesAndCartClear() throws Exception {User c=user("atomic@example.com",UserRole.CUSTOMER);Address a=address(c);Product good=product("Atomic good",5,"10",ProductStatus.ACTIVE,VendorStatus.APPROVED,true);Product bad=product("Atomic bad",5,"10",ProductStatus.ARCHIVED,VendorStatus.APPROVED,true);add(c,good,2);add(c,bad,1);checkout(c,a).andExpect(status().isConflict());assertThat(orders.count()).isZero();assertThat(products.findById(good.getId()).orElseThrow().getStockQuantity()).isEqualTo(5);assertThat(cartItems.count()).isEqualTo(2);}

 @Test void historyShowsOnlyOwnOrdersNewestFirstWithPagination() throws Exception {User c=user("history@example.com",UserRole.CUSTOMER);User other=user("history-other@example.com",UserRole.CUSTOMER);Address a=address(c);orders.saveAndFlush(order(c,a,"MH-OLD",OrderStatus.PENDING));orders.saveAndFlush(order(c,a,"MH-NEW",OrderStatus.PENDING));orders.saveAndFlush(order(other,address(other),"MH-OTHER",OrderStatus.PENDING));mvc.perform(get("/api/orders").header("Authorization",token(c)).param("page","0").param("size","1")).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(2)).andExpect(jsonPath("$.totalPages").value(2)).andExpect(jsonPath("$.content.length()").value(1)).andExpect(jsonPath("$.content[0].orderNumber").value("MH-NEW"));}

 @Test void detailsIncludeSnapshotsAndForeignOrderIsForbidden() throws Exception {User c=user("details@example.com",UserRole.CUSTOMER);User other=user("details-other@example.com",UserRole.CUSTOMER);Address a=address(c);Order o=orders.saveAndFlush(order(c,a,"MH-DETAIL",OrderStatus.PENDING));orderItems.saveAndFlush(new OrderItem(o,1L,2L,"Historical Name",new BigDecimal("75"),2));mvc.perform(get("/api/orders/{id}",o.getId()).header("Authorization",token(c))).andExpect(status().isOk()).andExpect(jsonPath("$.deliveryCity").value("Colombo")).andExpect(jsonPath("$.items[0].productName").value("Historical Name"));mvc.perform(get("/api/orders/{id}",o.getId()).header("Authorization",token(other))).andExpect(status().isForbidden());mvc.perform(get("/api/orders/{id}",Long.MAX_VALUE).header("Authorization",token(c))).andExpect(status().isNotFound());}

 @Test void pendingOrderCancellationRestoresStockAndCannotRepeat() throws Exception {User c=user("cancel@example.com",UserRole.CUSTOMER);Address a=address(c);Product p=product("Cancel stock",0,"20",ProductStatus.OUT_OF_STOCK,VendorStatus.APPROVED,true);Order o=orders.saveAndFlush(order(c,a,"MH-CANCEL",OrderStatus.PENDING));orderItems.saveAndFlush(new OrderItem(o,p.getId(),p.getVendor().getId(),p.getName(),p.getPrice(),2));mvc.perform(patch("/api/orders/{id}/cancel",o.getId()).header("Authorization",token(c))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CANCELLED"));assertThat(products.findById(p.getId()).orElseThrow().getStockQuantity()).isEqualTo(2);assertThat(products.findById(p.getId()).orElseThrow().getStatus()).isEqualTo(ProductStatus.ACTIVE);mvc.perform(patch("/api/orders/{id}/cancel",o.getId()).header("Authorization",token(c))).andExpect(status().isConflict());}

 @Test void nonCancellableStatusesAndForeignCancellationAreRejected() throws Exception {User owner=user("cancel-owner@example.com",UserRole.CUSTOMER);User other=user("cancel-other@example.com",UserRole.CUSTOMER);Address a=address(owner);for(OrderStatus s:List.of(OrderStatus.PROCESSING,OrderStatus.SHIPPED,OrderStatus.DELIVERED)){Order o=orders.saveAndFlush(order(owner,a,"MH-"+s,s));mvc.perform(patch("/api/orders/{id}/cancel",o.getId()).header("Authorization",token(owner))).andExpect(status().isConflict());}Order pending=orders.saveAndFlush(order(owner,a,"MH-FOREIGN-CANCEL",OrderStatus.PENDING));mvc.perform(patch("/api/orders/{id}/cancel",pending.getId()).header("Authorization",token(other))).andExpect(status().isForbidden());}

 private void assertRejected(String key,ProductStatus ps,VendorStatus vs,boolean active,int stock,int qty)throws Exception{User c=user("reject-"+key+"@example.com",UserRole.CUSTOMER);Address a=address(c);Product p=product("Reject "+key,stock,"10",ps,vs,active);Cart cart=carts.saveAndFlush(new Cart(c));cartItems.saveAndFlush(new CartItem(cart,p,qty));checkout(c,a).andExpect(status().isConflict());}
 private org.springframework.test.web.servlet.ResultActions checkout(User c,Address a)throws Exception{return mvc.perform(post("/api/orders/checkout").header("Authorization",token(c)).contentType(MediaType.APPLICATION_JSON).content(checkout(a)));}
 private String checkout(Address a){return "{\"addressId\":"+a.getId()+",\"paymentMethod\":\"CASH_ON_DELIVERY\"}";}
 private void add(User c,Product p,int q){Cart cart=carts.findByCustomerId(c.getId()).orElseGet(()->carts.saveAndFlush(new Cart(c)));cartItems.saveAndFlush(new CartItem(cart,p,q));}
 private Order order(User c,Address a,String number,OrderStatus status){Order o=new Order(c,number,new BigDecimal("100"),new BigDecimal("300"),PaymentMethod.CASH_ON_DELIVERY,a.getFullName(),a.getPhone(),a.getAddressLine1(),null,a.getCity(),a.getDistrict(),a.getPostalCode());o.setStatus(status);return o;}
 private Address address(User c){return addresses.saveAndFlush(new Address(c,"Customer Name","0771234567","10 Main Street",null,"Colombo","Colombo","00100",true));}
 private Product product(String name,int stock,String price,ProductStatus ps,VendorStatus vs,boolean active){String k=UUID.randomUUID().toString();User u=user(k+"@example.com",UserRole.VENDOR);Vendor v=new Vendor(u,"Store "+k,"Description","123");v.setStatus(vs);v=vendors.saveAndFlush(v);Category cat=new Category("Category "+k,k,"Description");cat.setActive(active);cat=categories.saveAndFlush(cat);return products.saveAndFlush(new Product(v,cat,name,"Description",new BigDecimal(price),stock,null,ps));}
 private User user(String email,UserRole role){return users.saveAndFlush(new User("Order","Tester",email,encoder.encode("Password123"),role));}
 private String token(User u){return "Bearer "+jwt.generateToken(u);}
}
