package com.markethub.order;

import com.markethub.auth.JwtService; import com.markethub.user.*; import com.markethub.vendor.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Transactional
class VendorOrderWorkflowTests {
 @Autowired MockMvc mvc; @Autowired UserRepository users; @Autowired VendorRepository vendors; @Autowired OrderRepository orders; @Autowired OrderItemRepository items; @Autowired PasswordEncoder encoder; @Autowired JwtService jwt;

 @Test void vendorListingShowsOnlyRelatedOrdersAndVendorTotals() throws Exception {Vendor own=vendor("list-own@example.com");Vendor other=vendor("list-other@example.com");User customer=user("list-customer@example.com",UserRole.CUSTOMER);Order mixed=order(customer,"MH-MIXED",OrderStatus.PENDING);item(mixed,own,"Own A",new BigDecimal("10"),2);item(mixed,other,"Other",new BigDecimal("99"),1);item(mixed,own,"Own B",new BigDecimal("5"),1);Order unrelated=order(customer,"MH-UNRELATED",OrderStatus.PENDING);item(unrelated,other,"Other only",new BigDecimal("20"),1);mvc.perform(get("/api/vendor/orders").header("Authorization",token(own.getUser()))).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1)).andExpect(jsonPath("$.content[0].orderNumber").value("MH-MIXED")).andExpect(jsonPath("$.content[0].vendorItemCount").value(2)).andExpect(jsonPath("$.content[0].vendorSubtotal").value(25.00));}

 @Test void customerAndUnauthenticatedCannotListVendorOrders() throws Exception {User customer=user("vendor-api-customer@example.com",UserRole.CUSTOMER);mvc.perform(get("/api/vendor/orders").header("Authorization",token(customer))).andExpect(status().isForbidden());mvc.perform(get("/api/vendor/orders")).andExpect(status().isUnauthorized());}

 @Test void listingFiltersStatusAndPaginatesNewestFirst() throws Exception {Vendor vendor=vendor("filter-vendor@example.com");User customer=user("filter-customer@example.com",UserRole.CUSTOMER);Order pending=order(customer,"MH-PENDING",OrderStatus.PENDING);item(pending,vendor,"Pending",BigDecimal.TEN,1);Order shipped=order(customer,"MH-SHIPPED",OrderStatus.SHIPPED);item(shipped,vendor,"Shipped",BigDecimal.TEN,1);mvc.perform(get("/api/vendor/orders").header("Authorization",token(vendor.getUser())).param("status","SHIPPED")).andExpect(jsonPath("$.totalElements").value(1)).andExpect(jsonPath("$.content[0].orderNumber").value("MH-SHIPPED"));mvc.perform(get("/api/vendor/orders").header("Authorization",token(vendor.getUser())).param("page","0").param("size","1")).andExpect(jsonPath("$.size").value(1)).andExpect(jsonPath("$.totalPages").value(2)).andExpect(jsonPath("$.content[0].orderNumber").value("MH-SHIPPED"));}

 @Test void detailsExposeOnlyOwnItemsAndHideUnrelatedOrders() throws Exception {Vendor own=vendor("detail-own@example.com");Vendor other=vendor("detail-other@example.com");Order order=order(user("detail-customer@example.com",UserRole.CUSTOMER),"MH-DETAIL-VENDOR",OrderStatus.PENDING);item(order,own,"Visible",new BigDecimal("30"),2);item(order,other,"Hidden",new BigDecimal("100"),1);mvc.perform(get("/api/vendor/orders/{id}",order.getId()).header("Authorization",token(own.getUser()))).andExpect(status().isOk()).andExpect(jsonPath("$.vendorItems.length()").value(1)).andExpect(jsonPath("$.vendorItems[0].productName").value("Visible")).andExpect(jsonPath("$.vendorSubtotal").value(60.00)).andExpect(jsonPath("$..productName",org.hamcrest.Matchers.not(org.hamcrest.Matchers.hasItem("Hidden"))));mvc.perform(get("/api/vendor/orders/{id}",order.getId()).header("Authorization",token(vendor("unrelated@example.com").getUser()))).andExpect(status().isNotFound());mvc.perform(get("/api/vendor/orders/{id}",Long.MAX_VALUE).header("Authorization",token(own.getUser()))).andExpect(status().isNotFound());}

 @Test void vendorUpdatesOwnItemButCannotUpdateAnotherVendorsItem() throws Exception {Vendor own=vendor("update-own@example.com");Vendor other=vendor("update-other@example.com");Order order=order(user("update-customer@example.com",UserRole.CUSTOMER),"MH-UPDATE",OrderStatus.PENDING);OrderItem ownItem=item(order,own,"Own",BigDecimal.TEN,1);OrderItem foreign=item(order,other,"Foreign",BigDecimal.TEN,1);update(own,order,ownItem,"CONFIRMED").andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CONFIRMED"));update(own,order,foreign,"CONFIRMED").andExpect(status().isNotFound());}

 @Test void invalidTransitionsCancelledOrdersAndBackwardMovesAreRejected() throws Exception {Vendor vendor=vendor("transition-vendor@example.com");User customer=user("transition-customer@example.com",UserRole.CUSTOMER);Order pending=order(customer,"MH-SKIP",OrderStatus.PENDING);OrderItem pendingItem=item(pending,vendor,"Skip",BigDecimal.TEN,1);update(vendor,pending,pendingItem,"SHIPPED").andExpect(status().isConflict());Order cancelled=order(customer,"MH-CANCELLED-VENDOR",OrderStatus.CANCELLED);OrderItem cancelledItem=item(cancelled,vendor,"Cancelled",BigDecimal.TEN,1);update(vendor,cancelled,cancelledItem,"CONFIRMED").andExpect(status().isConflict());Order delivered=order(customer,"MH-DELIVERED-VENDOR",OrderStatus.DELIVERED);OrderItem deliveredItem=item(delivered,vendor,"Delivered",BigDecimal.TEN,1);deliveredItem.setStatus(OrderStatus.DELIVERED);items.saveAndFlush(deliveredItem);update(vendor,delivered,deliveredItem,"SHIPPED").andExpect(status().isConflict());}

 @Test void itemProgressSynchronizesOverallOrderStatus() throws Exception {Vendor vendor=vendor("sync-vendor@example.com");Order order=order(user("sync-customer@example.com",UserRole.CUSTOMER),"MH-SYNC",OrderStatus.PENDING);OrderItem item=item(order,vendor,"Sync",BigDecimal.TEN,1);update(vendor,order,item,"CONFIRMED").andExpect(status().isOk());assertStatus(order,OrderStatus.CONFIRMED);update(vendor,order,item,"PROCESSING").andExpect(status().isOk());assertStatus(order,OrderStatus.PROCESSING);update(vendor,order,item,"SHIPPED").andExpect(status().isOk());assertStatus(order,OrderStatus.SHIPPED);update(vendor,order,item,"DELIVERED").andExpect(status().isOk());assertStatus(order,OrderStatus.DELIVERED);}

 private void assertStatus(Order o,OrderStatus s){assertThat(orders.findById(o.getId()).orElseThrow().getStatus()).isEqualTo(s);}
 private org.springframework.test.web.servlet.ResultActions update(Vendor v,Order o,OrderItem i,String status)throws Exception{return mvc.perform(patch("/api/vendor/orders/{orderId}/items/{itemId}/status",o.getId(),i.getId()).header("Authorization",token(v.getUser())).contentType(MediaType.APPLICATION_JSON).content("{\"status\":\""+status+"\"}"));}
 private Order order(User customer,String number,OrderStatus status){Order o=new Order(customer,number,new BigDecimal("100"),new BigDecimal("300"),PaymentMethod.CASH_ON_DELIVERY,"Customer Name","0771234567","10 Main Street",null,"Colombo","Colombo","00100");o.setStatus(status);return orders.saveAndFlush(o);}
 private OrderItem item(Order o,Vendor v,String name,BigDecimal price,int quantity){return items.saveAndFlush(new OrderItem(o,Math.abs(UUID.randomUUID().getMostSignificantBits()),v.getId(),name,price,quantity));}
 private Vendor vendor(String email){User u=user(email,UserRole.VENDOR);Vendor v=new Vendor(u,"Store "+email,"Description","123");v.setStatus(VendorStatus.APPROVED);return vendors.saveAndFlush(v);}
 private User user(String email,UserRole role){return users.saveAndFlush(new User("Test","Customer",email,encoder.encode("Password123"),role));}
 private String token(User user){return "Bearer "+jwt.generateToken(user);}
}
