package com.markethub.admin;
import com.markethub.auth.JwtService; import com.markethub.category.*; import com.markethub.order.*; import com.markethub.product.*; import com.markethub.user.*; import com.markethub.vendor.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.UUID;
import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Transactional
class AdminManagementWorkflowTests{
 @Autowired MockMvc mvc;@Autowired UserRepository users;@Autowired VendorRepository vendors;@Autowired CategoryRepository categories;@Autowired ProductRepository products;@Autowired OrderRepository orders;@Autowired OrderItemRepository items;@Autowired PasswordEncoder encoder;@Autowired JwtService jwt;
 @Test void adminListsAndFiltersUsersSafely()throws Exception{User a=user("list-admin",UserRole.ADMIN);user("list-customer",UserRole.CUSTOMER);mvc.perform(get("/api/admin/users").header("Authorization",token(a)).param("role","CUSTOMER").param("status","ACTIVE")).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1)).andExpect(jsonPath("$.content[0].role").value("CUSTOMER")).andExpect(jsonPath("$.content[0].password").doesNotExist());}
 @Test void customerAndAnonymousCannotAccessAdmin()throws Exception{User c=user("blocked-customer",UserRole.CUSTOMER);mvc.perform(get("/api/admin/users").header("Authorization",token(c))).andExpect(status().isForbidden());mvc.perform(get("/api/admin/users")).andExpect(status().isUnauthorized());}
 @Test void adminDisablesUserAndDisabledUserCannotLogin()throws Exception{User a=user("disable-admin",UserRole.ADMIN);User c=user("disable-customer",UserRole.CUSTOMER);mvc.perform(patch("/api/admin/users/{id}/disable",c.getId()).header("Authorization",token(a))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("DISABLED"));mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+c.getEmail()+"\",\"password\":\"Password123\"}")).andExpect(status().isForbidden());}
 @Test void adminReEnablesUser()throws Exception{User a=user("enable-admin",UserRole.ADMIN);User c=user("enable-customer",UserRole.CUSTOMER);c.setStatus(UserStatus.DISABLED);users.saveAndFlush(c);mvc.perform(patch("/api/admin/users/{id}/enable",c.getId()).header("Authorization",token(a))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ACTIVE"));}
 @Test void adminCannotDisableSelf()throws Exception{User a=user("self-admin",UserRole.ADMIN);mvc.perform(patch("/api/admin/users/{id}/disable",a.getId()).header("Authorization",token(a))).andExpect(status().isConflict());}
 @Test void adminSuspendsApprovedVendorAndPublicProductsDisappear()throws Exception{User a=user("suspend-admin",UserRole.ADMIN);Vendor v=vendor("suspend-vendor",VendorStatus.APPROVED,UserRole.VENDOR);Product p=product(v,"Suspend Product",ProductStatus.ACTIVE,5);mvc.perform(patch("/api/admin/vendors/{id}/suspend",v.getId()).header("Authorization",token(a))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("SUSPENDED"));mvc.perform(get("/api/products/{id}",p.getId())).andExpect(status().isNotFound());}
 @Test void invalidVendorSuspensionReturnsConflict()throws Exception{User a=user("invalid-suspend-admin",UserRole.ADMIN);Vendor v=vendor("pending-vendor",VendorStatus.PENDING,UserRole.CUSTOMER);mvc.perform(patch("/api/admin/vendors/{id}/suspend",v.getId()).header("Authorization",token(a))).andExpect(status().isConflict());}
 @Test void adminListsAllProductsIncludingInactive()throws Exception{User a=user("products-admin",UserRole.ADMIN);Vendor v=vendor("products-vendor",VendorStatus.APPROVED,UserRole.VENDOR);Product p=product(v,"Inactive Product",ProductStatus.INACTIVE,5);mvc.perform(get("/api/admin/products").header("Authorization",token(a)).param("status","INACTIVE")).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1)).andExpect(jsonPath("$.content[0].id").value(p.getId()));}
 @Test void adminDeactivatesProduct()throws Exception{User a=user("deactivate-admin",UserRole.ADMIN);Product p=product(vendor("deactivate-vendor",VendorStatus.APPROVED,UserRole.VENDOR),"Active Product",ProductStatus.ACTIVE,5);mvc.perform(patch("/api/admin/products/{id}/deactivate",p.getId()).header("Authorization",token(a))).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("INACTIVE"));}
 @Test void customerCannotUseAdminProductEndpoints()throws Exception{mvc.perform(get("/api/admin/products").header("Authorization",token(user("product-customer",UserRole.CUSTOMER)))).andExpect(status().isForbidden());}
 @Test void adminListsAndFiltersAllOrders()throws Exception{User a=user("orders-admin",UserRole.ADMIN);User c=user("orders-customer",UserRole.CUSTOMER);order(c,"MH-PENDING-ADMIN",OrderStatus.PENDING,new BigDecimal("100"));order(c,"MH-DELIVERED-ADMIN",OrderStatus.DELIVERED,new BigDecimal("200"));mvc.perform(get("/api/admin/orders").header("Authorization",token(a)).param("status","DELIVERED")).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1)).andExpect(jsonPath("$.content[0].orderNumber").value("MH-DELIVERED-ADMIN"));}
 @Test void adminViewsOrderDetailsWithCustomerDeliveryItemsAndVendor()throws Exception{User a=user("detail-admin",UserRole.ADMIN);User c=user("detail-customer",UserRole.CUSTOMER);Vendor v=vendor("detail-vendor",VendorStatus.APPROVED,UserRole.VENDOR);Order o=order(c,"MH-DETAIL-ADMIN",OrderStatus.PENDING,new BigDecimal("100"));item(o,v);mvc.perform(get("/api/admin/orders/{id}",o.getId()).header("Authorization",token(a))).andExpect(status().isOk()).andExpect(jsonPath("$.customer.email").value(c.getEmail())).andExpect(jsonPath("$.delivery.city").value("Colombo")).andExpect(jsonPath("$.items[0].vendorName").value(v.getStoreName())).andExpect(jsonPath("$.customer.password").doesNotExist());}
 @Test void customerCannotAccessAdminOrders()throws Exception{mvc.perform(get("/api/admin/orders").header("Authorization",token(user("order-customer",UserRole.CUSTOMER)))).andExpect(status().isForbidden());}
 @Test void dashboardCountsAndSalesMatchDatabase()throws Exception{User a=user("dashboard-admin",UserRole.ADMIN);User c=user("dashboard-customer",UserRole.CUSTOMER);Vendor approved=vendor("dashboard-approved",VendorStatus.APPROVED,UserRole.VENDOR);vendor("dashboard-pending",VendorStatus.PENDING,UserRole.CUSTOMER);vendor("dashboard-suspended",VendorStatus.SUSPENDED,UserRole.VENDOR);product(approved,"Active",ProductStatus.ACTIVE,5);product(approved,"Out",ProductStatus.OUT_OF_STOCK,0);order(c,"MH-DASH-P",OrderStatus.PENDING,new BigDecimal("100"));order(c,"MH-DASH-D",OrderStatus.DELIVERED,new BigDecimal("200"));order(c,"MH-DASH-C",OrderStatus.CANCELLED,new BigDecimal("300"));mvc.perform(get("/api/admin/dashboard").header("Authorization",token(a))).andExpect(status().isOk()).andExpect(jsonPath("$.totalUsers").value(5)).andExpect(jsonPath("$.totalCustomers").value(2)).andExpect(jsonPath("$.totalVendors").value(3)).andExpect(jsonPath("$.activeVendors").value(1)).andExpect(jsonPath("$.pendingVendors").value(1)).andExpect(jsonPath("$.suspendedVendors").value(1)).andExpect(jsonPath("$.totalProducts").value(2)).andExpect(jsonPath("$.activeProducts").value(1)).andExpect(jsonPath("$.outOfStockProducts").value(1)).andExpect(jsonPath("$.totalOrders").value(3)).andExpect(jsonPath("$.pendingOrders").value(1)).andExpect(jsonPath("$.deliveredOrders").value(1)).andExpect(jsonPath("$.totalSales").value(300.0));}
 private String token(User u){return "Bearer "+jwt.generateToken(u);}private User user(String k,UserRole r){return users.saveAndFlush(new User("Test","User",k+"@example.com",encoder.encode("Password123"),r));}
 private Vendor vendor(String k,VendorStatus s,UserRole r){Vendor v=new Vendor(user(k,r),"Store "+k,"Description","123");v.setStatus(s);return vendors.saveAndFlush(v);}
 private Product product(Vendor v,String n,ProductStatus s,int stock){String k=UUID.randomUUID().toString();Category c=categories.saveAndFlush(new Category("Category "+k,k,"Description"));return products.saveAndFlush(new Product(v,c,n,"Description",BigDecimal.TEN,stock,null,s));}
 private Order order(User c,String n,OrderStatus s,BigDecimal subtotal){Order o=new Order(c,n,subtotal,BigDecimal.ZERO,PaymentMethod.CASH_ON_DELIVERY,"Customer Name","0771234567","10 Main",null,"Colombo","Colombo","00100");o.setStatus(s);return orders.saveAndFlush(o);}
 private void item(Order o,Vendor v){items.saveAndFlush(new OrderItem(o,999L,v.getId(),"Item",BigDecimal.TEN,1));}}