import{fireEvent,render,screen,waitFor}from"@testing-library/react";import{QueryClient,QueryClientProvider}from"@tanstack/react-query";import{MemoryRouter}from"react-router-dom";import App from"../App";import{AuthProvider}from"../features/auth/AuthContext";import{saveAuth}from"../features/auth/authStorage";import*as dashboardApi from"../api/adminDashboard";import*as governanceApi from"../api/adminGovernance";import*as oversightApi from"../api/adminOversight";import*as productsApi from"../api/products";
vi.mock("../api/adminDashboard",()=>({fetchAdminDashboard:vi.fn()}));vi.mock("../api/adminGovernance",()=>({fetchAdminUsers:vi.fn(),fetchAdminUser:vi.fn(),setAdminUserEnabled:vi.fn(),fetchAdminVendors:vi.fn(),fetchAdminVendor:vi.fn(),moderateVendor:vi.fn()}));vi.mock("../api/adminOversight",()=>({fetchAdminProducts:vi.fn(),fetchAdminProduct:vi.fn(),deactivateAdminProduct:vi.fn(),fetchAdminOrders:vi.fn(),fetchAdminOrder:vi.fn()}));vi.mock("../api/products",()=>({fetchCategories:vi.fn(),fetchProducts:vi.fn(),fetchProduct:vi.fn(),refineProductsBySearch:(p:unknown)=>p}));
const vendor={id:8,userId:3,storeName:"Island Store",description:"Local",phone:"071",status:"PENDING"as const,createdAt:"",updatedAt:""};const order={id:20,orderNumber:"MH-20",status:"PENDING"as const,customerId:4,customerName:"Ada Customer",total:26,paymentMethod:"CASH_ON_DELIVERY"as const,createdAt:"2026-01-01"};function show(path:string,role:"ADMIN"|"CUSTOMER"|"VENDOR"="ADMIN"){saveAuth({token:"jwt",user:{id:1,firstName:"Ann",lastName:"Admin",email:"a@a.com",role,status:"ACTIVE"}});const c=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={c}><MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{localStorage.clear();vi.resetAllMocks();vi.mocked(dashboardApi.fetchAdminDashboard).mockResolvedValue({totalUsers:10,totalCustomers:7,totalVendors:3,activeVendors:2,pendingVendors:1,suspendedVendors:0,totalProducts:20,activeProducts:18,outOfStockProducts:2,totalOrders:30,pendingOrders:4,deliveredOrders:20,totalSales:5000});vi.mocked(governanceApi.fetchAdminVendors).mockResolvedValue([vendor]);vi.mocked(governanceApi.fetchAdminVendor).mockResolvedValue(vendor);vi.mocked(governanceApi.moderateVendor).mockResolvedValue({...vendor,status:"APPROVED"});vi.mocked(oversightApi.fetchAdminOrders).mockResolvedValue({content:[order],page:0,size:10,totalElements:1,totalPages:1});vi.mocked(productsApi.fetchCategories).mockResolvedValue([])});
it("renders authoritative operational metrics and queues",async()=>{show("/admin");expect(await screen.findByRole("heading",{name:"Admin dashboard"})).toBeInTheDocument();expect(await screen.findByText("$5,000.00")).toBeInTheDocument();expect(screen.getByText("Pending vendor queue")).toBeInTheDocument();expect(screen.getByText("Island Store")).toBeInTheDocument();expect(screen.getByText("MH-20")).toBeInTheDocument()});
it("moves from dashboard vendor queue through approval",async()=>{show("/admin");fireEvent.click(await screen.findByText("Island Store"));fireEvent.click(await screen.findByRole("button",{name:"Approve"}));await waitFor(()=>expect(governanceApi.moderateVendor).toHaveBeenCalledWith(8,"approve"))});
it("shows dashboard API failures with retry",async()=>{vi.mocked(dashboardApi.fetchAdminDashboard).mockRejectedValue(new Error("Dashboard offline"));show("/admin");expect(await screen.findByRole("alert")).toHaveTextContent("Dashboard offline");expect(screen.getByRole("button",{name:"Try again"})).toBeInTheDocument()});
it("preserves security boundaries across all roles",async()=>{show("/admin","VENDOR");expect(await screen.findByRole("heading",{name:"Dashboard unavailable"})).toBeInTheDocument();localStorage.clear();const c=new QueryClient();render(<QueryClientProvider client={c}><MemoryRouter initialEntries={["/admin"]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>);expect(await screen.findByRole("heading",{name:"Sign in"})).toBeInTheDocument()});


