import{fireEvent,render,screen,waitFor}from"@testing-library/react";import{QueryClient,QueryClientProvider}from"@tanstack/react-query";import{MemoryRouter}from"react-router-dom";import App from"../App";import{AuthProvider}from"../features/auth/AuthContext";import{saveAuth}from"../features/auth/authStorage";import*as api from"../api/adminOversight";import*as productsApi from"../api/products";
vi.mock("../api/adminOversight",()=>({fetchAdminProducts:vi.fn(),fetchAdminProduct:vi.fn(),deactivateAdminProduct:vi.fn(),fetchAdminOrders:vi.fn(),fetchAdminOrder:vi.fn()}));vi.mock("../api/products",()=>({fetchCategories:vi.fn(),fetchProducts:vi.fn(),fetchProduct:vi.fn(),refineProductsBySearch:(p:unknown)=>p}));
const product={id:7,name:"Vendor Tea",description:"Fresh",price:12,stockQuantity:5,imageUrl:null,status:"ACTIVE"as const,categoryId:2,categoryName:"Groceries",vendorId:8,vendorName:"Island Store",createdAt:"2026-01-01",updatedAt:"2026-01-01",averageRating:0,reviewCount:0};const summary={id:20,orderNumber:"MH-20",status:"PENDING"as const,customerId:4,customerName:"Ada Customer",total:26,paymentMethod:"CASH_ON_DELIVERY"as const,createdAt:"2026-01-01"};const detail={...summary,subtotal:24,deliveryFee:2,customer:{id:4,name:"Ada Customer",email:"ada@example.com"},delivery:{fullName:"Ada",phone:"071",addressLine1:"Main Road",addressLine2:null,city:"Kandy",district:"Kandy",postalCode:"20000"},items:[{id:1,productId:7,vendorId:8,vendorName:"Island Store",productName:"Vendor Tea",unitPrice:12,quantity:2,subtotal:24,status:"PENDING"as const}]};
function show(path:string){saveAuth({token:"jwt",user:{id:1,firstName:"Ann",lastName:"Admin",email:"a@a.com",role:"ADMIN",status:"ACTIVE"}});const c=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={c}><MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{localStorage.clear();vi.resetAllMocks();vi.mocked(productsApi.fetchCategories).mockResolvedValue([{id:2,name:"Groceries",slug:"groceries",description:null}]);vi.mocked(api.fetchAdminProducts).mockResolvedValue({content:[product],page:0,size:10,totalElements:1,totalPages:1});vi.mocked(api.fetchAdminProduct).mockResolvedValue(product);vi.mocked(api.deactivateAdminProduct).mockResolvedValue({...product,status:"INACTIVE"});vi.mocked(api.fetchAdminOrders).mockResolvedValue({content:[summary],page:0,size:10,totalElements:1,totalPages:1});vi.mocked(api.fetchAdminOrder).mockResolvedValue(detail)});
it("filters, inspects, and moderates products",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);show("/admin/products");expect(await screen.findByText("Vendor Tea")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Product status"),{target:{value:"ACTIVE"}});await waitFor(()=>expect(api.fetchAdminProducts).toHaveBeenLastCalledWith(expect.objectContaining({status:"ACTIVE"})));fireEvent.click(screen.getByRole("link",{name:"Inspect"}));fireEvent.click(await screen.findByRole("button",{name:"Deactivate product"}));await waitFor(()=>expect(api.deactivateAdminProduct).toHaveBeenCalledWith(7))});
it("renders filtered orders and complete authorized details",async()=>{show("/admin/orders");fireEvent.change(await screen.findByLabelText("Order status"),{target:{value:"PENDING"}});await waitFor(()=>expect(api.fetchAdminOrders).toHaveBeenLastCalledWith(expect.objectContaining({status:"PENDING"})));fireEvent.click(screen.getByRole("link",{name:"MH-20"}));expect(await screen.findByRole("heading",{name:"Order MH-20"})).toBeInTheDocument();expect(screen.getByText(/ada@example.com/)).toBeInTheDocument();expect(screen.getByText(/Island Store/)).toBeInTheDocument();expect(screen.getByText("$26.00")).toBeInTheDocument()});
it("shows safe missing product and order states",async()=>{vi.mocked(api.fetchAdminProduct).mockRejectedValue({isAxiosError:true,response:{status:404}});show("/admin/products/99");expect(await screen.findByRole("alert")).toHaveTextContent("Product not found")});
it("surfaces list and moderation failures",async()=>{vi.mocked(api.fetchAdminOrders).mockRejectedValue(new Error("Orders offline"));show("/admin/orders");expect(await screen.findByRole("alert")).toHaveTextContent("Orders offline")});

