import{fireEvent,render,screen,waitFor}from"@testing-library/react";import{QueryClient,QueryClientProvider}from"@tanstack/react-query";import{MemoryRouter}from"react-router-dom";import App from"../App";import{AuthProvider}from"../features/auth/AuthContext";import{saveAuth}from"../features/auth/authStorage";import*as productApi from"../api/vendorProducts";import*as orderApi from"../api/vendorOrders";import*as marketplaceApi from"../api/products";import type{VendorProduct}from"../types/vendor";
vi.mock("../api/vendorProducts",()=>({fetchVendorProducts:vi.fn(),fetchVendorProduct:vi.fn(),createVendorProduct:vi.fn(),updateVendorProduct:vi.fn(),archiveVendorProduct:vi.fn()}));vi.mock("../api/vendorOrders",()=>({fetchVendorOrders:vi.fn(),fetchVendorOrder:vi.fn(),fetchVendorProfile:vi.fn(),updateVendorOrderItem:vi.fn()}));vi.mock("../api/products",()=>({fetchCategories:vi.fn(),fetchProducts:vi.fn(),fetchProduct:vi.fn(),refineProductsBySearch:(p:unknown)=>p}));
const tea:VendorProduct={id:7,name:"Vendor Tea",description:"Fresh",price:12,stockQuantity:5,imageUrl:null,status:"ACTIVE",categoryId:2,categoryName:"Groceries",vendorId:8,vendorName:"Island Store",createdAt:"2026-01-01",updatedAt:"2026-01-01",averageRating:0,reviewCount:0};let products:VendorProduct[];const order={orderId:20,orderNumber:"MH-20",customerName:"Ada Customer",status:"PENDING"as const,vendorItemCount:1,vendorSubtotal:24,createdAt:"2026-09-18T08:00:00Z"};const detail={...order,orderStatus:"PENDING"as const,deliveryCity:"Kandy",deliveryDistrict:"Kandy",vendorItems:[{orderItemId:4,productId:7,productName:"Vendor Tea",unitPrice:12,quantity:2,subtotal:24,status:"PENDING"as const}]};
function show(path:string,role:"VENDOR"|"CUSTOMER"|"ADMIN"="VENDOR"){saveAuth({token:"jwt",user:{id:8,firstName:"Vera",lastName:"Vendor",email:"vendor@example.com",role,status:"ACTIVE"}});const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{localStorage.clear();vi.resetAllMocks();products=[tea];vi.mocked(productApi.fetchVendorProducts).mockImplementation(async()=>({content:products,page:0,size:10,totalElements:products.length,totalPages:1}));vi.mocked(productApi.fetchVendorProduct).mockResolvedValue(tea);vi.mocked(productApi.createVendorProduct).mockImplementation(async input=>{const created={...tea,id:9,...input,description:input.description??"",imageUrl:input.imageUrl??null};products=[...products,created];return created});vi.mocked(productApi.updateVendorProduct).mockImplementation(async(_id,input)=>({...tea,...input,description:input.description??"",imageUrl:input.imageUrl??null}));vi.mocked(productApi.archiveVendorProduct).mockResolvedValue({...tea,status:"ARCHIVED"});vi.mocked(marketplaceApi.fetchCategories).mockResolvedValue([{id:2,name:"Groceries",slug:"groceries",description:null}]);vi.mocked(orderApi.fetchVendorProfile).mockResolvedValue({id:8,userId:8,storeName:"Island Store",description:null,phone:"071",status:"APPROVED",createdAt:"",updatedAt:""});vi.mocked(orderApi.fetchVendorOrders).mockResolvedValue({content:[order],page:0,size:10,totalElements:1,totalPages:1});vi.mocked(orderApi.fetchVendorOrder).mockResolvedValue(detail);vi.mocked(orderApi.updateVendorOrderItem).mockResolvedValue({...detail.vendorItems[0],status:"CONFIRMED"})});
it("renders owned products and archives with confirmation",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);show("/vendor/products");expect(await screen.findByText("Vendor Tea")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Archive"}));await waitFor(()=>expect(productApi.archiveVendorProduct).toHaveBeenCalledWith(7,expect.anything()))});
it("creates a backend-compatible product and returns to the list",async()=>{show("/vendor/products/new");fireEvent.change(await screen.findByLabelText("Product name"),{target:{value:"New Coffee"}});fireEvent.change(screen.getByLabelText("Category"),{target:{value:"2"}});fireEvent.change(screen.getByLabelText("Price"),{target:{value:"15"}});fireEvent.change(screen.getByLabelText("Stock quantity"),{target:{value:"3"}});fireEvent.click(screen.getByRole("button",{name:"Create product"}));await waitFor(()=>expect(productApi.createVendorProduct).toHaveBeenCalled());expect(await screen.findByText("New Coffee")).toBeInTheDocument()});
it("validates product forms and prepopulates owned edits",async()=>{show("/vendor/products/7/edit");expect(await screen.findByDisplayValue("Vendor Tea")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("Stock quantity"),{target:{value:"-1"}});fireEvent.click(screen.getByRole("button",{name:"Save changes"}));expect(await screen.findByText("Stock cannot be negative")).toBeInTheDocument();expect(productApi.updateVendorProduct).not.toHaveBeenCalled()});
it("shows a safe state for an unauthorized product",async()=>{vi.mocked(productApi.fetchVendorProduct).mockRejectedValue({isAxiosError:true,response:{status:403}});show("/vendor/products/99/edit");expect(await screen.findByRole("heading",{name:"Product unavailable"})).toBeInTheDocument()});
it("renders dashboard totals and vendor-safe recent orders",async()=>{show("/vendor");expect(await screen.findByRole("heading",{name:"Island Store"})).toBeInTheDocument();expect(screen.getAllByText("Products")).toHaveLength(2);expect(screen.getByText("Recent orders")).toBeInTheDocument();expect(screen.getByText("MH-20")).toBeInTheDocument()});
it("opens vendor order detail and performs the next valid transition",async()=>{show("/vendor/orders");fireEvent.click(await screen.findByRole("link",{name:"MH-20"}));expect(await screen.findByRole("heading",{name:"Order MH-20"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Mark confirmed"}));await waitFor(()=>expect(orderApi.updateVendorOrderItem).toHaveBeenCalledWith(20,4,"CONFIRMED"))});
it("enforces role and authentication protection",async()=>{show("/vendor/products","CUSTOMER");expect(await screen.findByRole("heading",{name:"Shop from trusted local vendors"})).toBeInTheDocument();localStorage.clear();const client=new QueryClient();render(<QueryClientProvider client={client}><MemoryRouter initialEntries={["/vendor"]}><AuthProvider><App/></AuthProvider></MemoryRouter></QueryClientProvider>);expect(await screen.findByRole("heading",{name:"Sign in"})).toBeInTheDocument()});
it("renders product and order API failure states",async()=>{vi.mocked(productApi.fetchVendorProducts).mockRejectedValue(new Error("Products offline"));show("/vendor/products");expect(await screen.findByRole("alert")).toHaveTextContent("Products offline")});

