package com.markethub.wishlist;
import com.markethub.auth.JwtService; import com.markethub.category.*; import com.markethub.product.*; import com.markethub.user.*; import com.markethub.vendor.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.util.UUID;
import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Transactional
class WishlistWorkflowTests {
 @Autowired MockMvc mvc; @Autowired WishlistItemRepository items; @Autowired UserRepository users; @Autowired VendorRepository vendors; @Autowired CategoryRepository categories; @Autowired ProductRepository products; @Autowired PasswordEncoder encoder; @Autowired JwtService jwt;
 @Test void wishlistItemSavesCorrectly(){Fixture f=fixture("save");WishlistItem item=items.saveAndFlush(new WishlistItem(f.customer,f.product));assertThat(item.getId()).isNotNull();assertThat(item.getCreatedAt()).isNotNull();assertThat(item.getProduct().getId()).isEqualTo(f.product.getId());}
 @Test void uniqueCustomerProductConstraintWorks(){Fixture f=fixture("unique");items.saveAndFlush(new WishlistItem(f.customer,f.product));assertThatThrownBy(()->items.saveAndFlush(new WishlistItem(f.customer,f.product))).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void customerCanSaveProduct()throws Exception{Fixture f=fixture("add");add(f.customer,f.product).andExpect(status().isCreated());assertThat(items.existsByCustomerIdAndProductId(f.customer.getId(),f.product.getId())).isTrue();}
 @Test void unauthenticatedRequestIsRejected()throws Exception{Fixture f=fixture("anonymous");mvc.perform(post("/api/wishlist/{id}",f.product.getId())).andExpect(status().isUnauthorized());}
 @Test void vendorCannotUseCustomerWishlist()throws Exception{Fixture f=fixture("vendor");add(f.vendor.getUser(),f.product).andExpect(status().isForbidden());}
 @Test void duplicateProductCannotBeSavedTwice()throws Exception{Fixture f=fixture("duplicate");add(f.customer,f.product).andExpect(status().isCreated());add(f.customer,f.product).andExpect(status().isConflict());assertThat(items.count()).isEqualTo(1);}
 @Test void missingProductReturnsNotFound()throws Exception{User customer=user("missing",UserRole.CUSTOMER);mvc.perform(post("/api/wishlist/{id}",Long.MAX_VALUE).header("Authorization",token(customer))).andExpect(status().isNotFound());}
 @Test void customerCanRemoveOwnSavedProduct()throws Exception{Fixture f=fixture("remove");items.saveAndFlush(new WishlistItem(f.customer,f.product));remove(f.customer,f.product).andExpect(status().isNoContent());assertThat(items.count()).isZero();}
 @Test void anotherCustomerCannotRemoveSavedProduct()throws Exception{Fixture f=fixture("other-remove");items.saveAndFlush(new WishlistItem(f.customer,f.product));remove(user("other-remove-user",UserRole.CUSTOMER),f.product).andExpect(status().isNotFound());assertThat(items.count()).isEqualTo(1);}
 @Test void missingWishlistItemReturnsNotFound()throws Exception{Fixture f=fixture("missing-item");remove(f.customer,f.product).andExpect(status().isNotFound());}
 @Test void customerSeesOnlyOwnWishlist()throws Exception{Fixture f=fixture("only-own");Product second=product(f.vendor,f.category,"Other",ProductStatus.ACTIVE,2);items.saveAndFlush(new WishlistItem(f.customer,f.product));items.saveAndFlush(new WishlistItem(user("other-owner",UserRole.CUSTOMER),second));list(f.customer).andExpect(jsonPath("$.totalElements").value(1)).andExpect(jsonPath("$.content[0].productId").value(f.product.getId()));}
 @Test void newestSavedItemsAppearFirst()throws Exception{Fixture f=fixture("newest");Product newest=product(f.vendor,f.category,"Newest",ProductStatus.ACTIVE,2);items.saveAndFlush(new WishlistItem(f.customer,f.product));Thread.sleep(20);items.saveAndFlush(new WishlistItem(f.customer,newest));list(f.customer).andExpect(jsonPath("$.content[0].productId").value(newest.getId())).andExpect(jsonPath("$.content[1].productId").value(f.product.getId()));}
 @Test void listingPaginates()throws Exception{Fixture f=fixture("page");items.saveAndFlush(new WishlistItem(f.customer,f.product));items.saveAndFlush(new WishlistItem(f.customer,product(f.vendor,f.category,"Second",ProductStatus.ACTIVE,2)));mvc.perform(get("/api/wishlist").header("Authorization",token(f.customer)).param("page","0").param("size","1")).andExpect(status().isOk()).andExpect(jsonPath("$.content.length()").value(1)).andExpect(jsonPath("$.size").value(1)).andExpect(jsonPath("$.totalElements").value(2)).andExpect(jsonPath("$.totalPages").value(2));}
 @Test void listingReturnsSafeProductVendorAndCategoryData()throws Exception{Fixture f=fixture("safe");items.saveAndFlush(new WishlistItem(f.customer,f.product));list(f.customer).andExpect(jsonPath("$.content[0].wishlistItemId").exists()).andExpect(jsonPath("$.content[0].productName").value(f.product.getName())).andExpect(jsonPath("$.content[0].vendorName").value(f.vendor.getStoreName())).andExpect(jsonPath("$.content[0].categoryName").value(f.category.getName())).andExpect(jsonPath("$.content[0].email").doesNotExist()).andExpect(jsonPath("$.content[0].customerId").doesNotExist());}
 @Test void activeProductIsAvailable()throws Exception{assertAvailability(fixture("available"),true);}
 @Test void archivedProductRemainsVisibleButUnavailable()throws Exception{Fixture f=fixture("archived");f.product.setStatus(ProductStatus.ARCHIVED);products.saveAndFlush(f.product);assertAvailability(f,false);}
 @Test void outOfStockProductRemainsVisibleButUnavailable()throws Exception{Fixture f=fixture("stock");f.product.setStockQuantity(0);products.saveAndFlush(f.product);assertAvailability(f,false);}
 @Test void suspendedVendorProductRemainsVisibleButUnavailable()throws Exception{Fixture f=fixture("suspended");f.vendor.setStatus(VendorStatus.SUSPENDED);vendors.saveAndFlush(f.vendor);assertAvailability(f,false);}
 @Test void inactiveCategoryProductRemainsVisibleButUnavailable()throws Exception{Fixture f=fixture("category");f.category.setActive(false);categories.saveAndFlush(f.category);assertAvailability(f,false);}
 private void assertAvailability(Fixture f,boolean value)throws Exception{items.saveAndFlush(new WishlistItem(f.customer,f.product));list(f.customer).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].available").value(value)).andExpect(jsonPath("$.content[0].productId").value(f.product.getId()));}
 private org.springframework.test.web.servlet.ResultActions add(User u,Product p)throws Exception{return mvc.perform(post("/api/wishlist/{id}",p.getId()).header("Authorization",token(u)));}
 private org.springframework.test.web.servlet.ResultActions remove(User u,Product p)throws Exception{return mvc.perform(delete("/api/wishlist/{id}",p.getId()).header("Authorization",token(u)));}
 private org.springframework.test.web.servlet.ResultActions list(User u)throws Exception{return mvc.perform(get("/api/wishlist").header("Authorization",token(u)));}
 private String token(User u){return "Bearer "+jwt.generateToken(u);}
 private Fixture fixture(String key){String k=key+"-"+UUID.randomUUID();Vendor v=vendor(k);Category c=categories.saveAndFlush(new Category("Category "+k,k,"Description"));Product p=product(v,c,"Product "+k,ProductStatus.ACTIVE,5);return new Fixture(user(k+"-customer",UserRole.CUSTOMER),v,c,p);}
 private Product product(Vendor v,Category c,String name,ProductStatus status,int stock){return products.saveAndFlush(new Product(v,c,name,"Description",BigDecimal.TEN,stock,null,status));}
 private User user(String key,UserRole role){return users.saveAndFlush(new User("Test","Customer",key+"@example.com",encoder.encode("Password123"),role));}
 private Vendor vendor(String key){Vendor v=new Vendor(user(key+"-vendor",UserRole.VENDOR),"Store "+key,"Description","123");v.setStatus(VendorStatus.APPROVED);return vendors.saveAndFlush(v);}
 private record Fixture(User customer,Vendor vendor,Category category,Product product){}
}